repository_type: pipeline
nf_core_version: "2.14.1"

lint:
  nextflow_config:
    - manifest.homePage
  multiqc_config: False
  files_unchanged:
    - assets/email_template.html
    - assets/email_template.txt
    - assets/sendmail_template.txt
