repository_type: pipeline
nf_core_version: "2.14.1"

lint:
  nextflow_config:
    - manifest.homePage
    - manifest.name
  multiqc_config: False
  files_exist:
    - assets/nf-core-micronuclAI_nf_logo_light.png
    - docs/images/nf-core-micronuclAI_nf_logo_light.png
    - docs/images/nf-core-micronuclAI_nf_logo_dark.png
  files_unchanged:
    - assets/email_template.html
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - docs/README.md
